server:
  port: 8080
  servlet:
    context-path: /supplychain
spring:
  thymeleaf:
    mode: LEGACYHTML5
  http:
    multipart:  # 文件上传
      enabled: true
      max-file-size: 50MB #单个数据大小
      max-request-size: 100MB #总数据大小
  profiles:
    active: dev  #  开发环境
#    active: prod  #  生产环境
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
##################################自定义配置###############################################
request:
  limit:
    seconds: 30
caffine:
  duration: 50


